version: "3"

services:

  giftcards-db:
    image: postgres:latest
    container_name: giftcards-db
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    #volumes:
     # - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - giftcards-network

  giftcards:
    build: .
    image: almerindorehem/giftcards
    container_name: giftcards
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
        - giftcards-db
    networks:
      - giftcards-network

volumes:
  postgres-volume-data:
networks:
  giftcards-network:
    driver: bridge
